AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  GetHello:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Events:
        HelloApi:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
  
Outputs:
  HelloApiUrl:
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello
    Description: The URL of your Hello API Gateway you invoke with a GET request to retrieve a hello world